# Generated by Django 6.0.5 on 2026-05-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owasp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'vulnerability_categories',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=10)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('impact', models.TextField()),
                ('prevention', models.TextField()),
                ('vulnerable_code', models.TextField(blank=True, help_text='Exemple de code vulnérable')),
                ('vulnerable_code_language', models.CharField(default='python', max_length=30)),
                ('secure_code', models.TextField(blank=True, help_text='Version corrigée du code')),
                ('secure_code_language', models.CharField(default='python', max_length=30)),
                ('references', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vulnerabilities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='vulnerabilities.vulnerabilitycategory')),
            ],
            options={
                'verbose_name': 'Vulnérabilité',
                'db_table': 'vulnerabilities',
                'ordering': ['-severity', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='vulnerabilities.vulnerability')),
            ],
            options={
                'db_table': 'vulnerability_views',
                'unique_together': {('vulnerability', 'user')},
            },
        ),
    ]
