# Generated by Django 6.0.5 on 2026-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
